package model.service;

import java.sql.CallableStatement;

import model.view.TargetCartoon1VOImpl;

import oracle.jbo.server.ApplicationModuleImpl;
import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Tue Feb 25 10:15:14 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class AppModuleImpl extends ApplicationModuleImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public AppModuleImpl() {
    }

    /**
     * Container's getter for TargetCartoon1VO1.
     * @return TargetCartoon1VO1
     */
    public ViewObjectImpl getTargetCartoon1VO1() {
        return (ViewObjectImpl)findViewObject("TargetCartoon1VO1");
    }

    /**
     * Container's getter for TargetCartoon1TempVO1.
     * @return TargetCartoon1TempVO1
     */
    public ViewObjectImpl getTargetCartoon1TempVO1() {
        return (ViewObjectImpl)findViewObject("TargetCartoon1TempVO1");
    }
    
    
 
}
