package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Thu Apr 09 08:39:35 BDT 2020
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TargetCartoon1VOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TargetCartoon1VOImpl() {
    }


}
