package model.view;

import oracle.jbo.server.ViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Fri Oct 08 09:59:51 BDT 2021
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class TargetCartoon1TempVOImpl extends ViewObjectImpl {
    /**
     * This is the default constructor (do not remove).
     */
    public TargetCartoon1TempVOImpl() {
    }
}
